version: '3'

services:

  laravel:
    image: lucianovsjr/fc-php:prod
    container_name: laravel
    networks:
      - laranet

  nginx:
    image: lucianovsjr/fc-nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - 8080:80

networks:
  laranet:
    driver: bridge